# Quotes for AutoBio 🤘

# English Quotes ☺️
ENGLISH_QUOTES = [

    "Best way to earn respect is By treating others with respect 😊",
    "Win in silence. Let them think you're losing. 😏",
    "Even if the sloppy people get together, they’ll just end up being used",
    "The biggest slap to your enemies is your success.‌‌ 🤗",
    "When I pray, coincidences happen, and when I don't, they don't.",
    "Winners never quit and Quitters Never win. 😌",
    "Miracles aren’t my thing, but I’m sure we can come to an arrangement.",
    "Emotions are hard, but that’s why they make you strong",
    "It’s better to move forward than stay stuck in the past",
    "Desire shouldn’t be contained, it’s unnatural.",
    "There's no other way to go but forward.",
    "If the pain doesn't kill me, it will only make me stronger.",
    "When angels fall, they also… rise.",
    "Destiny is just the embodiment of the soul's desire to grow.",
    "Regret piles up around us like books we have never read.",
    "A smile is the easiest way out of a difficult situation.",
    "Somebody told me I’m a failure, I’ll prove them wrong.",
    "Failing doesn’t give you a reason to give up, as long as you believe.",
    "If you don’t share someone’s pain, you can never understand them",
    "Once you question your own belief it’s over.",
    "When you give up, your dreams and everything else they’re gone",
    "When a man learns to love, he must bear the risk of hatred.",
    "Even the strongest of opponents always has a weakness",
    "Failure is the only opportunity to begin again.",
    "Harsh words can’t solve problems; action will",
    "Smile is the best way to get away with trouble even if its a fake one",
    "It’s foolish to fear what we’ve yet to see and know.",
    "People’s lives don’t end when they die. It ends when they lose faith.",
    "No matter how things may seems to change, never forget who you are.",
    "Never forget who you are, for the world surely won’t.",
    "Once you’ve accepted your flaws, no one can use them against you",
    "In the end, there is no greater motivation than revenge.",
    "Life happens wherever you are, whether you make it or not",
    "Being alone is better than being with the wrong person",
    "Even with no magical powers… I’ll become the magic emperor.",
    "Gravel may be gravel, but me? I’m gravel that shatters diamonds!",
    "Sacrifice your ethics, your morals, Sacrifice your soul to your task",
    "We know the stories but sometimes its hard to separate fact from truth",
    "Being weak is nothing to be ashamed of… Staying weak is!",
    "And if you love, love their darkness too, not just their light. 🤘",
    "A lion doesn't concern itself with the opinion of sheep.",
    "It's a cruel and random world, but the chaos is all so beautiful",
    "It is only through the eyes of others that our lives have any meaning",
    "Sometimes losing people makes you find yourself. 😊",
    "Laughter is poison to fear.",
    "Some old wounds never truly heal,and bleed again at the slightest word",
    "You’re mine as I’m yours. And if we die, we die. But first we’ll live",
    "Strive not to be a success, but rather to be of value.",
    "Belive in yourself. You will survive whatever is coming. 😙",
    "is here any sweet is being sold here, you came to see. 😏",
    "It’s foolish to fear what we’ve yet to see and know.",
    "Do something today that your future self will thank you for. 👌",
    "There’s no meaning to a flower unless it blooms.",
    "Don't forget God when you get what you've prayed for. ☺️",
    "Be happy with what you have, while working for what you want. 😊",
    "You can only win when your mind is stronger than your emotions. ☺️",
    "Love for the dead is pointless.We fight to keep them alive, that's all",
    "Keep your dreams big and your worries small. 😌",
    "You can’t outrun destiny just because you’re terrified of it.",
    "If someone makes you happy, make them happier. 🤗",
    "Whatever you lack in talent, you make up for in confidence.😀",
    "Tag a friend who has been with you in your hard times. 😎",
    "Winning isn't everything, but wanting to win is. 😅",
    "Living is using time given to you. You cannot recall lost time.",
    "A champion is someone who gets up when he can't. 😄",
    "If you can believe it, the mind can achieve it. 😇",
    "A lesson without pain is meaningless.",
    "How can you move forward if you keep regretting the past.",
    "Game doesn't build character, it reveals character! 😗",
    "I Can't Stop Asking Myself. Why Do I Hate Myself So Much?!",
    "The next time I make you cry, they’ll be tears of joy!",
    "It’s you and me. I know it’s my destiny.",
    "If you train hard, you'll not only be hard, you'll be hard to beat. 🙂",
    "Me, give up? No way!",
    "Human beings are strong because we can change ourselves.",
    "I’ll leave tomorrow’s problem to tomorrow’s me.",
    "Wanna see what destruction looks like? Here it is in human form.",
    "You win some, lose some, and wreck some. 😅",
    "Age is no barrier. It's a limitation you put on your mind. 😌",
    "Even a piece of garbage has its pride.",
    "You cant gain something, without giving something in return",
    "Sometimes, forbidden fruit tastes the sweetest.",
    "Surpass the best to be the best",
    "The past can be a great teacher.",
    "Be yourself; everyone else is already taken.",
    "Be the change that you wish to see in the world.",
    "Life isn't about finding yourself. Life is about creating yourself.",
    "It's only legendary till someone proves it's real",
    "Trying to improve by learning from others that's what calls friendship",
    "Fools who don't respect the past are doomed to repeat it.",
    "Hard work is worthless for those that don’t believe in themselves.",
    "Set your goals high, and don't stop till you get there. 😊",
    "Statistics are like bikinis—they show a lot but not everything. 😁",
    "Searching for someone to blame is just a pain.",
    "Do not give reasons to love that you received!",
    "When we hit our lowest point, we are open to the greatest change.",
    "You miss 100 percent of the shots you don't take. 😌",
    "It Hurts, Not Being Accepted For Who You Are.",
    "Sometimes Betrayal Come From The Ones We Expect The Least",
    "There’s the easy way, and then there’s the right way.",
    "To the well-organized mind, death is but the next great adventure.",
    "Happiness is not something ready made. It comes from your own actions"
    "In the darkest of times, hope is something you give yourself.",
    "The way to get started is to quit talking and begin doing. 😄",
    "Sometimes we need to lose something before we can understand its value",
    "Your time is limited, so don't waste it living someone else's life.",
    "Chaos is the same as it’s always been. Humans just adapted better.",
    "People don't have power over us. We give it to them.",
    "Whether we wound or are wounded, the blood that flows is red.",
    "Even In the midst of chaos, there is also opportunity.",
    "To lose balance sometimes for love is part of living a balanced life."]
